### PR TITLE
Update _accessibility.scss

### PR DESCRIPTION
**Pull request by JABClari**
Focusable visually hidden element. Best for the "skip to content."

### CODE REVIEW

**Comment by sebastiano-guerriero** [comment]
Hi! That's very useful. 

Can you please change the code to (because it's a standalone utility class rather than a class modifier):

```scss
.sr-only-focusable { // focusable, visually hidden element
  &:not(:focus):not(:focus-within){
    @extend .sr-only
  }
}
```

and I will merge the pull request. Thanks

**Comment by JABClari** [comment]
ok. I'll do just that.

**Comment by JABClari** [comment]
Updated to utility.

**Comment by sebastiano-guerriero** [comment]
Thanks for contributing! 😊

**Pull request merged**
